### Variables 
@url = http://localhost:8888
@apiurl = {{url}}/api/modelo

GET {{url}}/ping
Accept: application/json

### Listar 1 cliente
GET {{apiurl}}/cliente/1
Accept: application/json

### Listar todos os clientes
GET {{apiurl}}/cliente
Accept: application/json

### Adicionar um cliente
POST {{apiurl}}/cliente
Content-Type: application/json

{
  "nome": "Cliente 4",
  "cpf": "4",
  "dt_nasc": "13/08/1969",
  "telefones": [
    "4832453548",
    "4832215526"
  ]
}

