// Code generated by MockGen. DO NOT EDIT.
// Source: src/modules/cliente/application/create/usecase/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=src/modules/cliente/application/create/usecase/interfaces.go -destination=src/modules/cliente/application/create/usecase/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/valdinei-santos/api-modelo-clean-arch/src/modules/cliente/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockIUsecase is a mock of IUsecase interface.
type MockIUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIUsecaseMockRecorder
}

// MockIUsecaseMockRecorder is the mock recorder for MockIUsecase.
type MockIUsecaseMockRecorder struct {
	mock *MockIUsecase
}

// NewMockIUsecase creates a new mock instance.
func NewMockIUsecase(ctrl *gomock.Controller) *MockIUsecase {
	mock := &MockIUsecase{ctrl: ctrl}
	mock.recorder = &MockIUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUsecase) EXPECT() *MockIUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIUsecase) Execute(stamp string, p *dto.Request) (*dto.OutputDefault, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", stamp, p)
	ret0, _ := ret[0].(*dto.OutputDefault)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockIUsecaseMockRecorder) Execute(stamp, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIUsecase)(nil).Execute), stamp, p)
}

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockIRepository) Save(stamp string, p *dto.Cliente) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", stamp, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIRepositoryMockRecorder) Save(stamp, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIRepository)(nil).Save), stamp, p)
}

// SaveTelefone mocks base method.
func (m *MockIRepository) SaveTelefone(stamp string, t *dto.Telefone) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTelefone", stamp, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTelefone indicates an expected call of SaveTelefone.
func (mr *MockIRepositoryMockRecorder) SaveTelefone(stamp, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTelefone", reflect.TypeOf((*MockIRepository)(nil).SaveTelefone), stamp, t)
}
