### Variables 
@url = http://localhost:8888
@apiurl = {{url}}/api/modelo

GET {{url}}/ping
Accept: application/json

### Listar 1 cliente
GET {{apiurl}}/cliente/1
Accept: application/json

### Listar todos os clientes
GET {{apiurl}}/cliente
Accept: application/json

### Adicionar um cliente
POST {{apiurl}}/cliente
Content-Type: application/json

{
  "nome": "Cliente 4",
  "cpf": "4",
  "dt_nasc": "13/08/1969",
  "telefones": [
    "4832453548",
    "4832215526"
  ]
}

### CLIENTE 02

### Listar 1 cliente
GET {{apiurl}}/cliente02/1
Accept: application/json

### Listar todos os clientes
GET {{apiurl}}/cliente02
Accept: application/json

### Adicionar um cliente
POST {{apiurl}}/cliente02
Content-Type: application/json

{
  "nome": "Cliente 6",
  "cpf": "6",
  "dt_nasc": "13/08/1959",
  "telefones": [
    "4832453500",
    "4832215500"
  ]
}


### CLIENTE 03

### Listar 1 cliente
GET {{apiurl}}/cliente03/1
Accept: application/json

### Listar todos os clientes
GET {{apiurl}}/cliente03
Accept: application/json

### Adicionar um cliente
POST {{apiurl}}/cliente03
Content-Type: application/json

{
  "nome": "Cliente 7",
  "cpf": "7",
  "dt_nasc": "13/08/1978",
  "telefones": [
    "4832453504",
    "4832215504"
  ]
}
