### Variables 
@url = http://localhost:8888
@apiurl = {{url}}/api/modelo

GET {{url}}/ping
Accept: application/json

### Listar 1 cliente
GET {{apiurl}}/cliente/1
Accept: application/json

### Listar todos os clientes
GET {{apiurl}}/cliente
Accept: application/json

### Listar 1 cliente com telefones
GET {{apiurl}}/cliente/1/telefones
Accept: application/json

### Listar todos os clientes com telefones
GET {{apiurl}}/cliente/telefones
Accept: application/json

### Adicionar um cliente
POST {{apiurl}}/cliente
Content-Type: application/json

{
  "nome": "Cliente 4",
  "cpf": "4",
  "dt_nasc": "13/08/1969",
  "telefones": [
    "4832453548",
    "4832215526"
  ]
}

### CLIENTE 02

### Listar 1 cliente
GET {{apiurl}}/cliente02/1
Accept: application/json

### Listar todos os clientes
GET {{apiurl}}/cliente02
Accept: application/json

### Adicionar um cliente
POST {{apiurl}}/cliente02
Content-Type: application/json

{
  "nome": "Cliente 6",
  "cpf": "6",
  "dt_nasc": "13/08/1959",
  "telefones": [
    "4832453500",
    "4832215500"
  ]
}

### TELEFONE

### Listar todos os telefones de um CPF
GET {{apiurl}}/telefone/1
Accept: application/json

### Adicionar um telefone ao CPF x
POST {{apiurl}}/telefone
Content-Type: application/json

{
  "cpf": "1",
  "numero": "4832453504"
}

### CLIENTE

### Listar 1 cliente
GET {{apiurl}}/cliente/1
Accept: application/json

### Listar todos os clientes
GET {{apiurl}}/cliente
Accept: application/json

### Adicionar um cliente
POST {{apiurl}}/cliente
Content-Type: application/json

{
  "nome": "Cliente 1",
  "cpf": "1",
  "dt_nasc": "13/08/1978",
  "telefones": [
    "4832453504",
    "4832215504"
  ]
}
