### Variables 
@url = http://localhost:8888
@apiurl = {{url}}/api/modelo

GET {{url}}/ping
Accept: application/json

### TELEFONE

### Listar todos os telefones de um CPF
GET {{apiurl}}/telefone/1
Accept: application/json

### Adicionar um telefone ao CPF x
POST {{apiurl}}/telefone
Content-Type: application/json

{
  "cpf": "1",
  "numero": "4832453504"
}

### CLIENTE

### Listar 1 cliente
GET {{apiurl}}/cliente/1
Accept: application/json

### Listar todos os clientes
GET {{apiurl}}/cliente
Accept: application/json

### Adicionar um cliente
POST {{apiurl}}/cliente
Content-Type: application/json

{
  "nome": "Cliente 12",
  "cpf": "12",
  "dt_nasc": "16/06/1988",
  "telefones": [
    "4832453507",
    "4832215507"
  ]
}

### Adicionar um cliente com Telefones
POST {{apiurl}}/cliente/telefones
Content-Type: application/json

{
  "nome": "Cliente 13",
  "cpf": "13",
  "dt_nasc": "16/06/1988",
  "telefones": [
    "4832453507",
    "4832215507"
  ]
}

### PRODUTO

### Listar 1 produto
GET {{apiurl}}/produto/1
Accept: application/json

### Listar todos os produtos
GET {{apiurl}}/produto
Accept: application/json

### Adicionar um prpoduto
POST {{apiurl}}/produto
Content-Type: application/json

{
  "nome": "Produto 4",
  "descricao": "Descrição detalhada do Produto 4",
  "preco": 12.45,
  "qtd_estoque": 20,
  "categoria": "Eletrodomésticos",
  "fl_ativo": "S"
}