CREATE SEQUENCE PRODUTO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE PRODUTO (
    ID               NUMBER PRIMARY KEY, -- ID gerado pela sequência
    NOME             VARCHAR2(50) NOT NULL,
    DESCRICAO        VARCHAR2(100) NOT NULL,
    PRECO            NUMBER(10, 2) NOT NULL,
    QTD_ESTOQUE      NUMBER DEFAULT 0,
    CATEGORIA        VARCHAR2(50),
    DATA_CRIACAO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FL_ATIVO         CHAR(1) DEFAULT 'S'
);

-- Exemplo de trigger para preencher o ID automaticamente
CREATE OR REPLACE TRIGGER PRODUTO_BI
BEFORE INSERT ON PRODUTO
FOR EACH ROW
BEGIN
    :NEW.ID := PRODUTO_SEQ.NEXTVAL;
END;
/