// Code generated by MockGen. DO NOT EDIT.
// Source: application/cliente/get01/usecase/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=application/cliente/get01/usecase/interfaces.go -destination=application/cliente/get01/usecase/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	usecase "github.com/valdinei-santos/api-modelo-clean-arch/src/application/cliente/get01/usecase"
	entities "github.com/valdinei-santos/api-modelo-clean-arch/src/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIUsecase is a mock of IUsecase interface.
type MockIUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIUsecaseMockRecorder
}

// MockIUsecaseMockRecorder is the mock recorder for MockIUsecase.
type MockIUsecaseMockRecorder struct {
	mock *MockIUsecase
}

// NewMockIUsecase creates a new mock instance.
func NewMockIUsecase(ctrl *gomock.Controller) *MockIUsecase {
	mock := &MockIUsecase{ctrl: ctrl}
	mock.recorder = &MockIUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUsecase) EXPECT() *MockIUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIUsecase) Execute(stamp, cpf string) (*usecase.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", stamp, cpf)
	ret0, _ := ret[0].(*usecase.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockIUsecaseMockRecorder) Execute(stamp, cpf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIUsecase)(nil).Execute), stamp, cpf)
}

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// QueryLoadDataCliente mocks base method.
func (m *MockIRepository) QueryLoadDataCliente(stamp, cpf string) (*entities.Cliente, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryLoadDataCliente", stamp, cpf)
	ret0, _ := ret[0].(*entities.Cliente)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryLoadDataCliente indicates an expected call of QueryLoadDataCliente.
func (mr *MockIRepositoryMockRecorder) QueryLoadDataCliente(stamp, cpf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryLoadDataCliente", reflect.TypeOf((*MockIRepository)(nil).QueryLoadDataCliente), stamp, cpf)
}

// QueryLoadDataTelefone mocks base method.
func (m *MockIRepository) QueryLoadDataTelefone(stamp, cpf string) ([]entities.Telefone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryLoadDataTelefone", stamp, cpf)
	ret0, _ := ret[0].([]entities.Telefone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryLoadDataTelefone indicates an expected call of QueryLoadDataTelefone.
func (mr *MockIRepositoryMockRecorder) QueryLoadDataTelefone(stamp, cpf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryLoadDataTelefone", reflect.TypeOf((*MockIRepository)(nil).QueryLoadDataTelefone), stamp, cpf)
}
